youtarr_db_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39363731653037363732363931373632636232393632313564353363646139616235336463623266
          3266396336313936353866373630616330323537386333380a613832343734343235633665666462
          37386535326330626261363136613032343030336530613435326133326239303061336438623266
          6539646563393331370a366265363964626235616137356639353033353363353534643138626434
          33646433313231393531313432373239666466323835656433343663323236326261

proton_privoxy_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66373136333665313436663834363636306235623266363066356334353563386133393161613763
          3563316362313336393531376433636336383365303936650a333462346133626163373031336332
          61656664663637333961316266323036656166633038353035643131363330373362386561653536
          3164663531356431370a663933643731616264346461613663653435346135623636333831356262
          61386337363431656134336139313538336662393466343162363965656538383838

proton_privoxy_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39396539663235376638376333386431326136333962303761366365333765613462303131663763
          3363393734323436353436346536316166663934323734320a316437356539653838363432323461
          39656361346333343937376133316465313962306336356435386563303737393134663366316232
          6461613431613231650a356331313836366461306337313866353166663530313836376532653762
          65373164323561643439643235653330363333643864376135343231353538383538