youtarr_db_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39363731653037363732363931373632636232393632313564353363646139616235336463623266
          3266396336313936353866373630616330323537386333380a613832343734343235633665666462
          37386535326330626261363136613032343030336530613435326133326239303061336438623266
          6539646563393331370a366265363964626235616137356639353033353363353534643138626434
          33646433313231393531313432373239666466323835656433343663323236326261