---
install_docker_repo_url: https://download.docker.com/linux/raspbian

media_mountpoint: /multimedia
media_subfolders:
  - movies
  - tv
  - music
  - photos
  - pictures
  - downloads
  - transcode
  - youtube
  - downloads

plex_group_id: "2000"
plex_timezone: Etc/UTC
plex_user_id: "2000"
plex_version: docker

prowlarr_base_dir: /opt/plex/prowlarr
prowlarr_port: 9696

radarr_base_dir: /opt/plex/radarr
radarr_port: 7878

qbittorrent_base_dir: /opt/plex/qbittorrent
qbittorrent_health_check_host: one.one.one.one
qbittorrent_health_check_interval: 300
qbittorrent_health_check_silent: "1"
qbittorrent_lan_network: 192.168.1.0/24
qbittorrent_name_servers: 1.1.1.1,1.0.0.1
qbittorrent_torrent_port: 6881
qbittorrent_umask: "002"
qbittorrent_vpn_enabled: "yes"
qbittorrent_vpn_type: openvpn
qbittorrent_webui_port: 8080

sonarr_base_dir: /opt/plex/sonarr

youtarr_auth_enabled: ""
youtarr_auth_preset_username: admin
youtarr_base_dir: /opt/plex/youtarr
youtarr_db_gid: "999"
youtarr_db_name: youtarr
youtarr_db_port: 3221
youtarr_db_uid: "999"
youtarr_gid: "2000"
youtarr_log_level: info
youtarr_timezone: Etc/UTC
youtarr_uid: "2000"
youtarr_youtube_output_dir: /multimedia/youtube
