---
- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Start Plex container
  ansible.builtin.command:
    cmd: docker compose -f /opt/plex/docker-compose.yml up -d
