---
- name: Install Docker
  ansible.builtin.include_tasks: install.yml

- name: Run Plex tasks
  ansible.builtin.include_tasks: plex.yml

- name: Run Prowlarr tasks
  ansible.builtin.include_tasks: prowlarr.yml

- name: Run Gluetun tasks
  ansible.builtin.include_tasks: gluetun.yml

- name: Run qBittorrent tasks
  ansible.builtin.include_tasks: qbittorrent.yml

- name: Run Youtarr tasks
  ansible.builtin.include_tasks: youtarr.yml
